
name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: echo $TITLE
      - run: go build .
      - run: ./prlint -s $GITHUB_SHA
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}