
name: Pull Request
on:
  pull_request:
    branches:
      - 'main'
env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go build .
      - run: ./prlint -s $GITHUB_SHA
